
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjnlzdxwodurnooflsen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqbmx6ZHh3b2R1cm5vb2Zsc2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODY0NjQsImV4cCI6MjA2MTQ2MjQ2NH0.49k-yi77mBvWNxonG7PCjIjXEAU3nOlROl4PxxeEWvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Fetches compatibility data from demo_compatibility table
export async function fetchCompatibilityData() {
  try {
    const { data, error } = await supabase
      .from('demo_compatibility')
      .select('compat')
      .order('created_at', { ascending: false })
      .limit(1);

    if (error) {
      console.error('Error fetching compatibility data:', error);
      return null;
    }

    // Return the compatibility data if available
    if (data && data.length > 0) {
      return data[0].compat;
    }

    // Return sample data if nothing is found
    return {
      components: ["CPU", "GPU", "RAM", "Motherboard", "Storage"],
      links: [
        { 
          source: "CPU", 
          target: "Motherboard", 
          status: "true",
          reason: "소켓 타입이 LGA1700으로 CPU와 메인보드가 일치합니다."
        },
        { 
          source: "CPU", 
          target: "Memory", 
          status: "true",
          reason: "CPU는 DDR5를 지원하고, 메모리도 DDR5입니다."
        },
        { 
          source: "Memory", 
          target: "Motherboard", 
          status: "true",
          reason: "메인보드는 최대 128GB DDR5를 지원하며, 메모리는 32GB DDR5입니다."
        },
        { 
          source: "Motherboard", 
          target: "Case", 
          status: "false",
          reason: "ATX 폼팩터 메인보드는 선택한 미니타워 케이스에 장착되지 않습니다."
        },
        { 
          source: "Case", 
          target: "PSU", 
          status: "true",
          reason: "PSU는 표준 ATX 사이즈로 케이스와 호환됩니다."
        },
        { 
          source: "Case", 
          target: "GPU", 
          status: "false",
          reason: "GPU 길이(340mm)가 케이스 최대 지원 길이(320mm)를 초과합니다." 
        }
      ]
    };
  } catch (error) {
    console.error('Error fetching compatibility data:', error);
    return null;
  }
}
