
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjnlzdxwodurnooflsen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqbmx6ZHh3b2R1cm5vb2Zsc2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODY0NjQsImV4cCI6MjA2MTQ2MjQ2NH0.49k-yi77mBvWNxonG7PCjIjXEAU3nOlROl4PxxeEWvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Fetches compatibility data from demo_compatibility table
export async function fetchCompatibilityData() {
  try {
    const { data, error } = await supabase
      .from('demo_compatibility')
      .select('compat')
      .order('created_at', { ascending: false })
      .limit(1);

    if (error) {
      console.error('Error fetching compatibility data:', error);
      return null;
    }

    // Return the compatibility data if available
    if (data && data.length > 0) {
      return data[0].compat;
    }

    // Return sample data if nothing is found
    return {
      components: ["CPU", "GPU", "RAM", "Motherboard", "Storage", "PSU", "Case"],
      "CPU_Motherboard": true,
      "CPU_Motherboard_Reason": "소켓 타입이 LGA1700으로 CPU와 메인보드가 일치합니다.",
      "CPU_RAM": true,
      "CPU_RAM_Reason": "CPU는 DDR5를 지원하고, 메모리도 DDR5입니다.",
      "RAM_Motherboard": true,
      "RAM_Motherboard_Reason": "메인보드는 최대 128GB DDR5를 지원하며, 메모리는 32GB DDR5입니다.",
      "Motherboard_Case": false,
      "Motherboard_Case_Reason": "ATX 폼팩터 메인보드는 선택한 미니타워 케이스에 장착되지 않습니다.",
      "Case_PSU": true,
      "Case_PSU_Reason": "PSU는 표준 ATX 사이즈로 케이스와 호환됩니다.",
      "Case_GPU": false,
      "Case_GPU_Reason": "GPU 길이(340mm)가 케이스 최대 지원 길이(320mm)를 초과합니다.",
      "EdgeCase": null,
      "Replace": null
    };
  } catch (error) {
    console.error('Error fetching compatibility data:', error);
    return null;
  }
}
